### ISSUE TITLE
Current search result stays highlighted

### ISSUE THREAD

**Issue by tterranigma** [qxxxb/vim-searchhi#1]
I haven't found a way to clear the current search result's highlighting. After I search and I am done, I often issue `:nohlsearch` to clear the highlighting. But this does not clean the current search result's highlighting. Using `g:searchhi_clear_all_autocmds` has no result either. Is there a way to remove the highlighting?

**Comment by qxxxb** [comment]
`<Plug>(searchhi-clear-all)` will clear all search highlighting, and `<Plug>(searchhi-clear)` will clear only the highlight on the current search

**Comment by tterranigma** [comment]
You are right. Sorry for the trouble.
