### ISSUE TITLE
Is there a way to clear highlight all matches even the last chosen one?

### ISSUE THREAD

**Issue by roachsinai** [qxxxb/vim-searchhi#10]
The last chosen one keep highlight even I change the content of other lines in insert mode.

Thanks in advance!

**Comment by qxxxb** [comment]
Sorry I don't think I understand. Could you be more specific? If you want to turn off highlighting in insert mode you can try:
```vim
let g:searchhi_clear_all_autocmds = 'InsertEnter'
let g:searchhi_update_all_autocmds = 'InsertLeave'
```

**Comment by roachsinai** [comment]
> If you want search highlighting to be cleared as soon as the cursor moves, use this:
>
> let g:searchhi_clear_all_asap = 1

What I expected is when I move left or right clear the highlight, but seems the choosen match highlight not cleared as the quote saying.

Check below image, the search word is `class`, but highlight still there even cursor is on word `Solution`:

![Screen Capture_select-area_20201014092259](https://user-images.githubusercontent.com/9500049/95932754-475c8780-0dff-11eb-9c61-b24a31cc0831.png)

**Comment by qxxxb** [comment]
I think the problem is that you have `vim-searchant` installed as well. Also you seem to be redefining searchhi autocmds. Here's a config I would suggest:
```diff
-Plug 'timakro/vim-searchant'
Plug 'qxxxb/vim-searchhi'
Plug 'osyo-manga/vim-anzu'

nmap n <Plug>(searchhi-n)
nmap N <Plug>(searchhi-N)
nmap * <Plug>(searchhi-*)
nmap g* <Plug>(searchhi-g*)
nmap # <Plug>(searchhi-#)
nmap g# <Plug>(searchhi-g#)
nmap gd <Plug>(searchhi-gd)
nmap gD <Plug>(searchhi-gD)

vmap n <Plug>(searchhi-v-n)
vmap N <Plug>(searchhi-v-N)
vmap * <Plug>(searchhi-v-*)
vmap g* <Plug>(searchhi-v-g*)
vmap # <Plug>(searchhi-v-#)
vmap g# <Plug>(searchhi-v-g#)
vmap gd <Plug>(searchhi-v-gd)
vmap gD <Plug>(searchhi-v-gD)

let g:searchhi_user_autocmds_enabled = 1
let g:searchhi_redraw_before_on = 1

-augroup searchhi
-    autocmd!
-    autocmd User SearchHiOn AnzuUpdateSearchStatusOutput
-    autocmd User SearchHiOff echo g:anzu_no_match_word
-augroup END
augroup searchhi
    autocmd!

    autocmd User SearchHiOn
        \ set guicursor=
            \c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,
            \n-v:block-blinkwait20-blinkon20-blinkoff20 |
        \ AnzuUpdateSearchStatusOutput

    autocmd User SearchHiOff set guicursor& | echo g:anzu_no_match_word
augroup END

let g:searchhi_clear_all_asap = 1

nmap / <Plug>(searchhi-/)
nmap ? <Plug>(searchhi-?)

vmap / <Plug>(searchhi-v-/)
vmap ? <Plug>(searchhi-v-?)

```

**Comment by roachsinai** [comment]
That works, thanks a lot for your reply.

**Comment by qxxxb** [comment]
No problem!
