### ISSUE TITLE
No such group or event: CmdLineLeave * silent call searchhi#await_cmdline_leave()

### ISSUE THREAD

**Issue by kbseah** [qxxxb/vim-searchhi#12]
Hello @qxxxb, I tried installing this plugin with Vundle on vim v7.4, however I get the following error message:

```
Error detected while processing function searchhi#await:
line    9:
E216: No such group or event: CmdLineLeave * silent call searchhi#await_cmdline_leave()
```

Do you know what might be causing this issue? Thanks!

**Comment by qxxxb** [comment]
It seems to be because the `CmdlineLeave` autogroup was only implement in Vim 8.0.1206, so you might need to upgrade in order for this plugin to work

**Comment by kbseah** [comment]
thanks for the explanation!
