### ISSUE TITLE
I'd like to deprecate vim-searchant in favor of vim-searchhi

### ISSUE THREAD

**Issue by timakro** [qxxxb/vim-searchhi#13]
This is not an issue report, I just didn't find another way to contact you. To cut right to the case, how would you feel about adding an unmaintained notice to https://github.com/timakro/vim-searchant and directing users to your project?

I discovered your project about a month ago and took a closer look today. And I have to say you did a perfect job! All use cases of vim-searchant seem to be covered by your plugin. Most importantly, your plugin fixes a bunch of longstanding vim-searchant bugs, including some that I deemed unfixable. I tested those with your plugin and they just work as expected:

* https://github.com/timakro/vim-searchant/issues/24
* https://github.com/timakro/vim-searchant/issues/21
* https://github.com/timakro/vim-searchant/issues/16
* https://github.com/timakro/vim-searchant/issues/7

If you agree I'll mark my plugin unmaintained and redirect users to your repository. What do you think?

**Comment by qxxxb** [comment]
Sounds good to me, and thanks for making vim-searchant! I was looked at your code a lot when I was writing this plugin :D

**Comment by timakro** [comment]
Done :)

**Comment by antoineco** [comment]
Thanks @timakro and @qxxxb! 👏  Searchant has been a life changer for me in many situations, and I'm glad to see there is a good alternative to it.

@timakro is there a way to mark the plugin as archived on Vim.org too? https://www.vim.org/scripts/script.php?script_id=5404
