### ISSUE TITLE
Clearing highlighting after moving cursor does not work if matches are on top of each other

### ISSUE THREAD

**Issue by mroavi** [qxxxb/vim-searchhi#14]
I enabled clearing the highlighting as soon as the cursor moves with:
```vim
let g:searchhi_clear_all_asap = 1
```
as described in the README.

 However, I noticed that if matched words are located above/below each other, then the highlight is not cleared.

Here is a GIF that demonstrates this:

![Peek 2021-08-04 16-42_searchhi_bug](https://user-images.githubusercontent.com/19517248/128201348-ebf5cdf1-2c44-4437-acaf-13d944c698b7.gif)

**Comment by qxxxb** [comment]
Thanks for the report, should be fixed now!

**Comment by mroavi** [comment]
The fix introduced another problem: using <kbd>*</kbd> on a word that is already in the search register does not highlight any match:

![Peek 2021-08-04 16-42_searchhi_bug2](https://user-images.githubusercontent.com/19517248/128248062-ee9d4e06-a846-458b-be79-fa3d3e81c984.gif)

**Comment by mroavi** [comment]
Ohh, wait, your latest commit  fe812e8 which closes #15 also fixed the issue above.
