### ISSUE TITLE
Inconsistent highlighting behavior of unique words in buffer

### ISSUE THREAD

**Issue by mroavi** [qxxxb/vim-searchhi#15]
I caught another small bug. I noticed that the highlighting behavior differs the first time a unique word is highlighted with respect from the subsequent times the same word is highlighted.

Here is a GIF demonstrating the above:

![Peek 2021-08-04 17-19_searchhi_highlight_single_word_bug](https://user-images.githubusercontent.com/19517248/128207545-0299d734-361b-4066-8a4a-5c79427015b8.gif)

I'm loving this plugin by the way. I've been searching for this functionality for several years and finally, I came across this plugin.

**Comment by qxxxb** [comment]
Thanks for the bug report and glad to see the plugin is useful for you :smiley:
