### ISSUE TITLE
Matches are unwantedly re-highlighted after exiting insert mode

### ISSUE THREAD

**Issue by mroavi** [qxxxb/vim-searchhi#16]
I have this option enabled:
```vim
let g:searchhi_clear_all_autocmds = 'InsertEnter'
```

However, when I return to normal mode and hover over a word that matches the previous search, then all the matches are unwantedly re-highlighled:

![Peek 2021-08-04 16-42_searchhi_insert_bug](https://user-images.githubusercontent.com/19517248/128251138-51cbbaea-cf11-41b0-baa3-e5fa1d1037ff.gif)

Your plugin is great. The other plugins that try to implement this functionality flicker. Yours doesn't.

**Comment by qxxxb** [comment]
Thanks should be fixed now!

**Comment by mroavi** [comment]
Thanks a lot! There's only one small annoyance with the fix. Entering and leaving insert mode moves the cursor one space to the left. Ideally, it should stay in the same position. Is there an easy fix for that? If not, I'm very happy with the current fix!

**Comment by qxxxb** [comment]
I think the character moving to the left is the default behavior for Vim

**Comment by mroavi** [comment]
You are completely right. Thanks again for the cool plugin!!
