### ISSUE TITLE
E1155: Cannot define autocommands for ALL events

### ISSUE THREAD

**Issue by mladenivkovic** [qxxxb/vim-searchhi#19]
Heya!

I've been getting this annoying error message recently:

```
Error detected while processing function searchhi#cmdline_leave_handler[1]..searchhi#update[5]..searchhi#listen:
line   18:
E1155: Cannot define autocommands for ALL events
```

It happens the first time I search for something after I open a file. Is there anything I can do about that?

Cheers, Mladen

**Comment by ms-yusuf** [comment]
My workaround for this problem is by using custom autocmd so I don't get the error from that function.

```
let g:searchhi_clear_all_autocmds = 'InsertEnter'
let g:searchhi_update_all_autocmds = 'InsertLeave'
```

**Comment by qxxxb** [comment]
Hey, sorry for the late response. What is your configuration and Vim/Neovim version? I'm haven't been to reproduce this, but my guess is that this issue occurs when `g:searchhi_clear_all_autocmds` and `g:searchhi_update_all_autocmds` are empty strings, which would cause issues here:
```vim
            execute 'autocmd! ' . g:searchhi_clear_all_autocmds .
                \ ' * silent call searchhi#clear_all()'

            execute 'autocmd! ' . g:searchhi_update_all_autocmds .
                \ ' * silent call searchhi#update_all()'
```

**Comment by bentilley** [comment]
There was a patch to vim 8 a while back that disabled the use of defining an autocommand for all events.

See https://github.com/vim/vim/commit/9a046fd08bcae319d39a4dbde2be81decee19013

I've got a potential fix here: https://github.com/qxxxb/vim-searchhi/pull/21 - only defining the autocommands if the global config variables are set. It a change of behaviour, but thought that it was better to allow user to configure their own events for vim8 ranther than guess a subset of events to add to the default config. Lemme know what you think?

Also, thanks for the plugin 👍 v useful stuff 🙏

**Comment by qxxxb** [comment]
Thanks for looking into this! The bug should be fixed by 6d3d595e84f12b2086b1c77db39da219c1736aa6 now, though I did not test it on vim8

**Comment by bentilley** [comment]
Tested on vim8 and looking good 👍

**Comment by gahr** [comment]
Vim 8.2, works fine, thanks a  lot!
