### ISSUE TITLE
Can't use `CursorMove` event in `searchhi_clear_all_autocmds`

### ISSUE THREAD

**Issue by tterranigma** [qxxxb/vim-searchhi#2]
When I set `g:searchhi_clear_all_autocmds='InsertEnter,CursorMove'` or `g:searchhi_clear_all_autocmds='CursorMove'`, no search result is highlighted. Pressing `n` moves on to the next result correctly though.

Is this a limitation of the plugin?

**Comment by qxxxb** [comment]
Thanks for reporting this! Since the plugin already relies on `CursorMoved`, that won't work.
I added `g:searchhi_clear_all_asap` and `g:searchhi_update_all_asap` which I think will do what you want.

**Comment by tterranigma** [comment]
This works great so far! Thank you for looking into this so fast!

**Comment by tterranigma** [comment]
Sth I noticed, the highlighting is removed once you get off the word that you searched for. For instance, if the search is for `find` and the text is

```
can you find me
```

then, if you press `l` and move on to the letter `i` in `find` the highlighting still stays on. You have to press either `j' or `k` or use `h` and `l` to move out of the word. 

No big deal, just mentioning.

**Comment by qxxxb** [comment]
4f828e877d3b50d5e464a913cbab592b8d6c6ceb should fix it, plus some other changes

**Comment by tterranigma** [comment]
It fixed it indeed!

**Comment by tterranigma** [comment]
Another issue I noticed with `searchhi_clear_all_asap` is that it breaks the vim-asterisk integration. When pressing `*` in the middle of a word all search matches are highlighted. But on pressing `n` the search highlighting is gone. On the second `n` the search highlighting comes back, etc. I guess vim-asterisk moves the cursor and triggers `searchhi_clear_all_asap`.

**Comment by qxxxb** [comment]
Turns out it was a bug with `asterisk#keeppos`. Should be fixed now!

**Comment by tterranigma** [comment]
I confirm it is fixed. Thank you for the great support!
